### ISSUE TITLE
dApp never passes the "The votes are being tallied right now..." status

### ISSUE THREAD

**Issue by udibr** [enigmampc/secret-contracts#3]

**Comment by andrewtam** [comment]
This alert is only shown when you ask for the poll status but the Enigma network is still performing the computation(it won’t show up automatically).

**Comment by udibr** [comment]
I think what happened is that I called `./deploy-ganache.sh` which re-installed the contracts and also erased the information about the registered EVM.

I re-run without calling this script and it looks like everything is working
